import type { LampPart } from '../types';

/**
 * Exports a single part as a binary STL file.
 */
export function exportSTL(part: LampPart, filename?: string): void {
  const vp = part.mesh.vertProperties;
  const np = part.mesh.numProp;
  const tv = part.mesh.triVerts;
  const numTriangles = tv.length / 3;

  const bufferSize = 84 + numTriangles * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);

  // 80-byte header
  const header = `Binary STL generated by LED Strip Lamp Designer - ${part.name}`;
  for (let i = 0; i < Math.min(80, header.length); i++) {
    view.setUint8(i, header.charCodeAt(i));
  }

  // 4-byte triangle count
  view.setUint32(80, numTriangles, true);

  let offset = 84;
  for (let i = 0; i < tv.length; i += 3) {
    const i0 = tv[i] * np;
    const i1 = tv[i + 1] * np;
    const i2 = tv[i + 2] * np;

    const ax = vp[i0], ay = vp[i0 + 1], az = vp[i0 + 2];
    const bx = vp[i1], by = vp[i1 + 1], bz = vp[i1 + 2];
    const cx = vp[i2], cy = vp[i2 + 1], cz = vp[i2 + 2];

    // Compute normal
    const abx = bx - ax, aby = by - ay, abz = bz - az;
    const acx = cx - ax, acy = cy - ay, acz = cz - az;
    let nx = aby * acz - abz * acy;
    let ny = abz * acx - abx * acz;
    let nz = abx * acy - aby * acx;
    const len = Math.sqrt(nx * nx + ny * ny + nz * nz);
    if (len > 0) {
      nx /= len; ny /= len; nz /= len;
    }

    view.setFloat32(offset, nx, true);
    view.setFloat32(offset + 4, ny, true);
    view.setFloat32(offset + 8, nz, true);
    offset += 12;

    view.setFloat32(offset, ax, true);
    view.setFloat32(offset + 4, ay, true);
    view.setFloat32(offset + 8, az, true);
    offset += 12;

    view.setFloat32(offset, bx, true);
    view.setFloat32(offset + 4, by, true);
    view.setFloat32(offset + 8, bz, true);
    offset += 12;

    view.setFloat32(offset, cx, true);
    view.setFloat32(offset + 4, cy, true);
    view.setFloat32(offset + 8, cz, true);
    offset += 12;

    view.setUint16(offset, 0, true); // attribute byte count
    offset += 2;
  }

  const blob = new Blob([buffer], { type: 'application/octet-stream' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `${part.id}_${part.name.replace(/\s+/g, '_').toLowerCase()}.stl`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
